services:
  # Container Aplikasi (PHP-FPM)
  app:
    build:
      context: .
    container_name: safedrugs-app
    volumes:
      - .:/var/www/html
    networks:
      - safedrugs-network

  # Container Web Server (Nginx)
  web:
    image: nginx:alpine
    container_name: safedrugs-web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - safedrugs-network

  # Container Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: safedrugs-db
    environment:
      POSTGRES_DB: safedrugs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safedrugs-network

networks:
  safedrugs-network:
    driver: bridge

volumes:
  postgres_data: